### ISSUE TITLE
Create Drawer Context/Provider - Update existing drawers

### ISSUE THREAD

**Issue by cdnicoll** [ocupop/iot-inspector-client#25]
Using react context/provider. Create a drawer system.

For reference, I created a modal sample for DGGT. Many similarities would apply here.

https://github.com/ocupop/dggt-application/commit/cddf4c0b58d06ea3455d900e841ff4d677a9eceb

**Comment by nathanielfostanperry** [comment]
Functionality is in place. Need to add in transitions/animations for the slide out
